### ISSUE TITLE
Choose the default doc to show for repositories with multiple elements

### ISSUE THREAD

**Issue by morethanreal** [PolymerElements/iron-doc-viewer#32]
I would like a way to choose which doc page is shown by default for repositories with multiple elements.

**Comment by mbleigh** [comment]
Sorry to be pedantic, but this is actually an [iron-component-page](https://github.com/PolymerElements/iron-component-page) issue now. Since my work on doc viewer, it is simply a set of display elements for hydrolysis descriptors. All of the logic and switching are on component page now.

I mention this primarily because this issue should be fixed, so if you file it on component page I'll go fix it soon :smile:

**Comment by morethanreal** [comment]
Cool, filed https://github.com/PolymerElements/iron-component-page/issues/12
