### ISSUE TITLE
The demo page of the iron-doc-viewer is blank & the doc page for iron-component-page is missing

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-doc-viewer#50]
_From @lozandier on June 11, 2015 0:27_

The demos demonstrating `iron-doc-viewer` is currently blank. Verified by @arthurevans being indeed the case for the element's demo page it seems fit to file this as a bug since no bug has been already filed for this problem. 

It seems warrantable for this to be fixed, as well as a demo page for `iron-component-page`. 

_Copied from original issue: Polymer/polymer#1826_

**Comment by tjsavage** [comment]
_From @sorvell on June 15, 2015 23:13_

This is the issue tracker for the Polymer core library. We'll get this moved to an appropriate location.

**Comment by atotic** [comment]
Got it! Some components (mostly authored by me), contain following line in bower.json:

```
  "ignore": [
    "/.*",
    "/test/",
    "/demo/"
  ],
```

I copied it from `seed-element`.
This causes polymer-element-catalog `bower install` not to install demo pages. 
Following repos have this problem:

geo-location
google-analytics
google-chart
google-map
google-signin
iron-doc-viewer
iron-jsonp-library
more-routing
paper-styles
prism-element
seed-element

We can either fix all these, or not use "--production" flag when doing `bower install` for polymer-element-catalog. I believe this is the right thing to do, because usually you do not want demo pages in production.

**Comment by atotic** [comment]
Looking further into this, there is no way to force bower to install ignored files. Our only option to making catalog work is removing ignore for demos. That also means all polymer sites will contain running demos.

**Comment by atotic** [comment]
All components have been fixed, and versions bumped.
