### ISSUE TITLE
Section headers need anchor-id attribute

### ISSUE THREAD

**Issue by purdrew** [PolymerElements/iron-doc-viewer#87]
### Description

The `scrollToAnchor` method currently works by scrolling to the element with an `anchor-id` attribute that matches the hash. The section headers (Properties, Methods, Events) are clickable links which update the url hash. However, since they don't have `anchor-id` attributes appropriately set, its not possible to use the `scrollToAnchor` method to bring them into view.
### Expected outcome

Section headers should be able to be scrolled into view.
### Actual outcome

Doesn't :-)
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by arthurevans** [comment]
Alternately, we could switch everything to use IDs instead of the custom anchor-id. Not only would this fix the noted problem, it'd help search identify the correct chunk of the page (and it would keep our link-checker from complaining about links to methods and properties, although that's a comparatively minor advantage).

**Comment by aomarks** [comment]
All headers are deep-linkable in the 3.0 version that was just published.
